language: java
#sudo: required
install:
  - sudo pip install ansible
script: 
  - mvn clean deploy --settings travis/settings.xml
  - ./trigger_portal.sh
cache: 
  directories:
    - $HOME/.m2
branches:
  only:
    - master
jdk:
  - oraclejdk8
env:
  global:
    - secure: "f+7Jg+zp2id0TkcuC5zCVfMmduEXzBvwWCuxqfW5l0i2rJT02dLLlwENvPdYBZU6CKGJOZ6T9/AnzuwtPvVAM3lWQCGpjFesuON635/nVBySOWeOCRv58Z/MJRSifYAmmJ0/atjO53N2zD5osptYBESiqqW3S6MUHL4EpoF9hu7NOmlT0y4NeTx6o1NysDpMHllQj/U9purdgUmHHSvl27KzG+ogIbajBeeUFkd80T+TlocI70scwOxdqKDLKajtZh+LHTo/1k63UvifcxTZyf9hujM1yX1N/ZyPCA+A2gol6GhZxhrfEC3tGj0uUH375dRPoiEyyMkJh7zr6P7Q7Av3b0O6/2DUGf4lZN1Ku5xlj4LDa13BhtV/8vBxgSEHdHnZ5YCMh9SCyXC/4wrFPXEOEBtEVYkgBhg8K7l7k0VakRmY3fGJX5q8eCM1sLkZ3wplsbtK1KP3pm1ZcTgXymqruzQOhYy0HdiP1Zsp3ukJnaQEERVqphm77b6+jFMrXfAUv4QrgfO2orqBPzAzYkD1/0ymILLMTxJ9eh7uoaOEWSM9SMZxd3gFsjsTjKNgqBomw7g/XMSJx1SM6BDvIv/pXYMmRJgBwfriFSDl9okb8u5e9/Q0m2tCdsvMiwNNBlMh4AYt+XMSrJug0XdXV9JkyDWI+dfvAlO8BeePO1Q="
    - secure: "EPV2GZG72U0cZz6RAkpecr/pVUASpnwmmPDB5Ed8B2x9M8vNqPkxpKG1nSvcUdk/s0mmNpP8ldl9o+X4SptQykUXFRJUXxEe5/zoxFYQ361tCGQAJfECUPj/IYANNwUMaDwQl2HbQANjJQfh+XEtfArzl77pN0IKXrmOZL31LU1QQI1HCqzh6/ILSipZpxWZ6fnQYW9x6AXdOAue5yxcdx5d1xBA/juDbGSDBYPbRJAralnpOYaSp5TuviwURK5uBp8XI1U5EbP9XTUx9swBhotUnthXBvt+KCf9yrrqTWL+Jy1FmZB831pKz6/EJzyR2TAC1cRI5Ct3BEPhb6ousxjs8F+PSCpvAMb+a6beS39F3HbdO8ixUX7IypYsD28g4Kq1FQQk9hTlaAlpvor7hPry/RoNwbIrvMz4YsOnGiK0hZLkkcoGzkfQRMQFZNfeXEaNKG8pu0mrSVwTahrYQ0I98YbqMgtOBLp71AgmfwyYZXJQC7w8SB6y/yaAQ2k84s3IPTJD/hvIPGL5/VcI2LyVTnCUyUU7UE0ajwIFZ9Wuxo2k8pk5H2BFsn1htcr+jlveVv6dLFht/0C2bscI+M3bOSizUSNCn1WjPRt4eKrGwgyVBuwe89GQAvtYU0HMwPds8Cq3fljwHHxkrdgr1lPp61JYJG4JcQwKqfejTaQ="
    # Travis Token
    - secure: "oK81D3qw4sK1loLKl8ARmpJgZeZE7m++WufPbV26tWDDCzQBK06F4vTipIuV7WM/W+lgViOU6gFmGC4IGGZ2Mk3NSf4BvZBH+UbFsdGVOT9mPeltrFVtap3ZtXqE+3hhCA2zZt3t31b7v0PDgQWB93z4mkYIL7POeZRGxT7vmYhA1FTuK0/O/VHS/VUqCLqawCc9F80nPEhVT1qQwQ5CTCUnwIrnGXWYNL0atUC9DYmhd8J2I10iQOOTTDeL79a2R5B/D6KJ1AQAdTZPatd56ELsfXDoeEeAAxxPJ2xABbhiOR3Q2FxQnuiHsiOwS/UOvfUNBKMw2KrFhHs7f1dSUIhpyouzE9BvQ61MQl4corhACWM/Kz7nn0WBk3Y/Ii6garD1tACG2KCOoWi83iEvnoJPC08JJg11Mt7ljZSMXcam+mJuvAenDNNvZgNyPAgbQOyx3qSt7u0G9x9rRwpVZhsyz5UyK+xhqAUQjWYWy23AjM7Xs/Da5nHoQeJHAx42pLUXfaf5iu5eEOvAIoPoGsv4dAIGl4VMS9c9b5TQeuqpYiB/fgbj3s4pM7gFFk1F9tmeCPmh1s8phWo/zgh2+fUl/ExbetsSG8PfbOEy40UauatqzBYbd30MzaHNaUQb81j1jy9fL+rIfgrKfTBrrX7Q1GZxVpgnwC+nRt1rano="
