language: java
script: "echo $CI_DEPLOY_USERNAME && mvn clean deploy --settings travis/settings.xml"
install: true
cache: 
  directories:
    - $HOME/.m2
  branches:
    only:
      - master
  jdk:
    - oraclejdk8
  env:
    global:
      - secure: "WIuCPJJtd55Elf4elh24B5brlNCWfLjSQv9kKN8FzgWG5aSysCHFOpxMcF8YIBGypa/+ENxVlcnGANzj4oj9xb3cTTikdBPfwgtEruzdn7kOIGcHOqKU3SuXpVKqjlWJVH/0sBjqgOdAZLUc6fNYPS+kJVmhFEwCAh2V81gNhjZd2iJ8IGZKSv1popYA5dhgmoL5ORu2hMJeroWyDaGBwYvjMi3VnVGrFyCbIG7rPU1fgV1ElLSfOoTjHFOCcT9TWks6ek22SVDgL0Ja6qIlcDI2bKtUzohrSYDbyyMfusEbTQZ82Jb6Gj+HRubFgd2q/NG27TXxUwx60OFhnmiBMEF5kqLmyjMWLfBpBIImEh3AO1qUAUSN8poepDFiyz73NTcAoSh4IG9UwFvw2LpmNFJgKTXq36W4GFeWNuKgGQYrnpMk6e8zwsoelUHCiXNdyQyIYVqoZ1hA07BUwjV6aC1tfrbxawTpLN1kr0yUA8ifJ2ntVr28Fd8GEMPWU8gQu1Jh4zzF/6slh7f/Q5Bs66Q4WfMV782n+pxEYOdJIu1rOVwnco/3MMu6+NYmKhF2tfEFP+qOMDWapi9JIXYz6AA8CGLqfZps71MDtqz+tA19zfqGHKWodK+fk7wirogGPrdkt6JSzbWRjtCMxjT6+Vcn+ZNW7/L6nFeWmIcphS8="
      - secure: "KyIx8TjFxax3SX3XbrXWCV6Uzg4dEc6bbvc78YA5wLfIvnnn/f7VtV7NLofkBIcwcd84sQ2dK+eJBWtrW6AvOdARSRioCVCQ2IBfgbZwyy6P3Z8QVzxOjNxZLmWKdJGsl4z/m2AmBiWoT36KH/+VENRRdNXmxIpxSX2jvM47ixXYxx+kcyTGgCJ6+AhY/Mt0JdRX2aA4Sjagi4zgs8NpQtnlXS0OBRYWELAwigOan1QOr0khwUgbLON8RFS907YqLdqK36khZ6dr2uic6u7ThOEmgSod1uNohWvnsRjeO/CG/9OrulI2ewwJJpMvxDjUrCuoRAzKW1qIzAEpVevm+On3wNP9a+2wsouA3evZCVGaBR4syYr+EEB/d1TORbRpEWLTGIgPSifKnMmsInbfBhXX8IpHckiTQ1UDgRP32AndQzkmIa+CA1QfegVNK4hk0yovxqxvRC0t+RLg+rOFM/+wfpLPnIBQJU+fYU+2r3gJ3yyM2K1t6tpqXc9L8SN1uj2H1RXQ0jYZjVGkySwCRpUYxXsdKETYJzHnTFlu8ChBkCldLgfcNSlxR4xmZd/n/PQC/68nMo4i7RXnJxknu2J4oi1wP+qrEAqwPe1012cDELMAw+HQEVarlsgntyGpXxsNE3yaZCh+P7y1S5rDS3shlAHOwBSZjyexo0u6LKA="