language: java
script: "mvn clean deploy --settings travis/settings.xml"
install: true
cache: 
  directories:
    - $HOME/.m2
  branches:
    only:
      - master
  jdk:
    - oraclejdk8
  env:
    global:
      - secure: "oIYtQUVKqTvNrOOICnEpLtcufIcOMQtLi6kALh7pNnT5EeXumO5kp6LoPAGWJICHRdngVdk8lsc8fLBgF4iYK//ssifRHRKtc0pqNZHCjg2LuaGj+vR/mtUI7NJmX3U4rmn52hiVC2kN4F3Cu12bX7WAXT4W9s2tEEu19gYFZnuS9oHUIYR6YvlF1vpnt8ezrz/GMrroLZcCbM0xKNSSefhsMyExJLIt1DmV8RnEgAa1G63uo/x0f2E908HDABfGFHk5Wq+BuxNgWbLLCJsPrgcz+fXge/iCBPdSzMWpy4POUorq6hZ+Wevn+udlPJRUqebcENGmsWf4gLgBZ2xdO1H5ydfQrRY/8BsthwsACYd3Iqe3O9fhri+N8i4pA0lJBu9I4mpYSs+mqDdOwFvlTVCnjWMXaLcaaY590cffZR031rzqCTNRpm6ypzOp+NlKq2WxYo4w6/mj5oNZETMzM2O2UIII9zRvBErlZ2904rqyPHhHRDba2MgENNB8kpg/K6kd07MifBm9xBp36bVrn0bppU4rOg5cB65oqkI7g+HMSDIVta1cM4MR2y67CpbfcEZ9QXaOUkUelQhK6A/YRmr1e65r/Yb4FU1BJju74F7VM4Bv1NEcfUyy3DHL3EAz6QtSxIwYghqjKG53zLun+NRE1PBaWOgd8xo22GrnU9Q="
      - secure: "fqG3n0JtDwWczRhzJVn2jKlVv/WXcaJuC2Oj6h/w5zYSsteWEP7y7CG4qU+MIUOxfwjXFh1O2kHlzNS22CgN3ECPmJAs2J1U2YBq6tQfqpKKDIsjBp3ZOr+0oBEI2VW/xbcHME/BQNbedItgvBkR0WxKo/YYXSzNHzj24JC9R1OBn2OaHIGYPzsqUHZPAQqpVqt/aWJYqOlqPQ6wAhRaJShnHD6CNOh5soKkH+zawf+91YjFfignHFhX2+KMMf876ZSl3RJLkBLdxF23YDUABBrgf7k0oBOQ1X6c7nfMNMV8gTSvIARlEo26sDgVffbglz0fOVkGfBoXfQwoqQgTvvAxvRMe67jxNPfqG3j1md41X+vRHO4m4j++5za4DSNbLhxInTPxRYRZqNoB+GFEsiWGvAJ05TpcAq33Hefula9kanSqZedgKWR7vpHschv2b8Fct57TSq8fVvEzi6fZ+bMGtgApd7bBWdd2mb/8xBabtCUBXM9zOGSVMwZESLWVQNd26CdRNFNXwAyE95J27HgrtkIJvQDpiVdH8RL60I5NHVDDPaoG7NjoQte8sBGrtTVbIbiocFVAkZUaS9I6qmCERQCTthmVz7cL8uBduMoM1U3eMGw3exM/QVko3uBQj877f5xf2h++GC7sIlJGO2wJsuyRn+FbGwMXZ2yD4Wg="