language: java
script: "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && mvn clean deploy --settings travis/settings.xml || mvn clean verify --settings travis/settings.xml"
install: true
cache: 
  directories:
    - $HOME/.m2
  branches:
    only:
      - master
  jdk:
    - oraclejdk8
    